apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: poc-configuration-management-previews
  namespace: flux-system
spec:
  path: ./clusters/develop-azure/poc-configuration-management/manifests
  interval: 1m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: fleet-online.devtick
  prune: true
  validation: client
  decryption:
    provider: sops
  postBuild:
    substitute:
      namespace: poc-configuration-management
      tag: 1.4.0
