trigger:
- main

resources:
  repositories:
  - repository: self
  - repository: templates
    type: git
    name: templates.azure-pipelines
    ref: refs/tags/1.6.3

variables:
- name: imageRepository
  value: 'poc/configuration-management'
- template: ci-ut-templates/branch-variables.yml@templates

stages:
- template: ci-ut-templates/get-git-version-template.yml@templates
  parameters:
    gitVersionConfigFilePath: 'gitversion.yaml'
- template: ci-ut-templates/build-app-stage.yml@templates
  parameters:
    imageRepository: '$(imageRepository)'
    projectPath: 'source/PocConfigurationManagement'
- template: ci-ut-templates/unit-tests-stage.DotNetCore.yml@templates-azure-pipelines
  parameters:
    testProjectPath: 'source/PocConfigurationManagement.Tests'
- template: ci-ut-templates/build-push-image-stage.yml@templates
  parameters:
    imageRepository: '$(imageRepository)'
    applicationName: 'PocConfigurationManagement'
